url: https://vonnw.github.io
description: Vonn's very cool nearly-useless site

defaults:
  scope:
    path: "/blog/"
  values:
    layout: "post"

excerpt_separator: <!--more-->
paginate: 8
paginate_path: "/blog/:num/"
permalink: "/blog/:year/:month/:day/:title/"

plugins:
  - jekyll-feed

feed:
  path: "/blog/feed.xml"
